;;; setup-lisp-directory --- setup the lisp directory     -*- lexical-binding: t -*-

;;; Code:

(require 'autoload)

;;;###autoload
(defun update-all-autoloads ()
  (interactive)
  (let ((generated-autoload-file (expand-file-name "loaddefs.el" site-lisp-directory))
        (make-backup-files nil))
    (when (not (file-exists-p generated-autoload-file))
      (with-current-buffer (find-file-noselect
                            generated-autoload-file)
        (insert ";;; automatically generated by init.el/update-all-autoloads -*- lexical-binding: t -*-")
        (save-buffer)))
    (update-directory-autoloads site-lisp-directory)))

;;;###autoload
(defun setup-lisp-directory ()
  (interactive)
  (let ((loaddefs-path (expand-file-name "loaddefs.el" site-lisp-directory)))
    (when (not (file-exists-p loaddefs-path))
      (update-all-autoloads))
    (load loaddefs-path nil t)))

(provide 'setup-lisp-directory)
;;; setup-lisp-directory.el ends here
