;;; site-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

;;; huhu



;;; Generated autoloads from clojure-indent-cond.el

(autoload 'schmir/indent-cond "clojure-indent-cond" "\
Indent cond statement.

(fn INDENT-POINT STATE)")


;;; Generated autoloads from cwc.el

(autoload 'cwc-cleanup "cwc" "\
Cleanup whitespace in current buffer.

This function runs `whitespace-cleanup-region' on all changed lines.  The buffer
has to be in `highlight-changes-mode'." t)
(autoload 'cwc-mode "cwc" "\
Minor mode for cleaning up whitespace only on changed lines.

This is a minor mode.  If called interactively, toggle the `Cwc mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `cwc-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'cwc-global-mode 'globalized-minor-mode t)
(defvar cwc-global-mode nil "\
Non-nil if Cwc-Global mode is enabled.
See the `cwc-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cwc-global-mode'.")
(custom-autoload 'cwc-global-mode "cwc" nil)
(autoload 'cwc-global-mode "cwc" "\
Toggle Cwc mode in many buffers.
Specifically, Cwc mode is enabled in all buffers where `cwc-mode'
would do it.

With prefix ARG, enable Cwc-Global mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

See `cwc-mode' for more information on Cwc mode.

(fn &optional ARG)" t)
(register-definition-prefixes "cwc" '("cwc-lighter"))


;;; Generated autoloads from ecomplete-extras.el

(register-definition-prefixes "ecomplete-extras" '("add-email-to-ecomplete" "compose-mail-to" "ecomplete--read-address" "email--name+address" "remove-email-from-ecomplete"))


;;; Generated autoloads from git-grep.el

(autoload 'git-grep "git-grep" "\
Run git grep, searching for REGEXP in FILES in directory DIR.
The search is limited to file names matching shell pattern FILES.
FILES may use abbreviations defined in `grep-files-aliases', e.g.
entering `ch' is equivalent to `*.[ch]'.

With \\[universal-argument] prefix, you can edit the constructed shell command line
before it is executed.
With two \\[universal-argument] prefixes, directly edit and run `grep-command'.

Collect output in a buffer.  While git grep runs asynchronously, you
can use \\[next-error] (M-x next-error), or \\<grep-mode-map>\\[compile-goto-error] in the grep output buffer,
to go to the lines where grep found matches.

This command shares argument histories with \\[rgrep] and \\[grep].

(fn REGEXP &optional FILES DIR)" t)


;;; Generated autoloads from my-lib.el

(autoload 'my/run-when-display-initialized "my-lib" "\
Run the given function when the display is initialized

(fn F)")
(autoload 'my/load-theme "my-lib" "\
Load the given `THEME' even when in daemon mode.

(fn THEME)")
(autoload 'my/sort-words-in-region "my-lib" "\
In active region sort words alphabetically in ascending order.
With prefix argument REVERSED use descending order.
Don't use this function on regions with nested brackets.

(fn BEG END &optional REVERSED)" t)
(autoload 'my/shift-left "my-lib" nil t)
(autoload 'my/shift-right "my-lib" nil t)


;;; Generated autoloads from setup-core.el

(register-definition-prefixes "setup-core" '("prot/keyboard-quit-dwim" "sbke" "try-complete-abbrev" "untabify-buffer" "yes-or-no-p"))


;;; Generated autoloads from setup-git.el

(register-definition-prefixes "setup-git" '("display-ansi-colors" "magit-display-ansi-colors" "yadm-status"))


;;; Generated autoloads from setup-python.el

(register-definition-prefixes "setup-python" '("my/eglot-workspace-config" "show-pyright-errors" "toggle-pyright-show-errors"))


;;; Generated autoloads from sup.el

(autoload 'sup-show-messages "sup")
(autoload 'sup-package-install "sup" "\


(fn PACKAGE)")
(register-definition-prefixes "sup" '("sup-"))

;;; End of scraped data

(provide 'site-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; site-loaddefs.el ends here
